### ISSUE TITLE
System requirements section needs update in Readme 

### ISSUE THREAD

**Issue by srivickynesh** [gluster/glusterfs-containers-tests#26]
Add a section to list Recommended system requirements.

**Comment by vamahaja** [comment]
Can you please point out which section needs to update?

**Comment by srivickynesh** [comment]
If you see the system requirement section,  1 Master node and 3 Storage nodes. This is the minimum requirement for the test to run.
Needs update with recommended configuration to run all the tests in a given setup.

**Comment by srivickynesh** [comment]
Readme updated with recommended system requirements.
